# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: huawei-telemetry.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Hw_Telemetry.Hw_Telemetry" do
    optional :node_id_str, :string, 1
    optional :subscription_id_str, :string, 2
    optional :sensor_path, :string, 3
    optional :proto_path, :string, 13
    optional :collection_id, :uint64, 4
    optional :collection_start_time, :uint64, 5
    optional :msg_timestamp, :uint64, 6
    optional :data_gpb, :message, 7, "Hw_Telemetry.Hw_TelemetryGPBTable"
    optional :collection_end_time, :uint64, 8
    optional :current_period, :uint32, 9
    optional :except_desc, :string, 10
    optional :product_name, :string, 11
    optional :encoding, :enum, 12, "Hw_Telemetry.Hw_Telemetry.Encoding"
    optional :data_str, :string, 14
    optional :ne_id, :string, 15
    optional :software_version, :string, 16
  end
  add_enum "Hw_Telemetry.Hw_Telemetry.Encoding" do
    value :Encoding_GPB, 0
    value :Encoding_JSON, 1
  end
  add_message "Hw_Telemetry.Hw_TelemetryGPBTable" do
    repeated :row, :message, 1, "Hw_Telemetry.Hw_TelemetryRowGPB"
    repeated :delete, :message, 2, "Hw_Telemetry.DataPath"
    optional :generator, :message, 3, "Hw_Telemetry.Generator"
  end
  add_message "Hw_Telemetry.Generator" do
    optional :generator_id, :uint64, 1
    optional :generator_sn, :uint32, 2
    optional :generator_sync, :bool, 3
  end
  add_message "Hw_Telemetry.Hw_TelemetryRowGPB" do
    optional :timestamp, :uint64, 1
    optional :content, :bytes, 11
  end
  add_message "Hw_Telemetry.DataPath" do
    optional :timestamp, :uint64, 1
    optional :path, :message, 2, "Hw_Telemetry.Path"
  end
  add_message "Hw_Telemetry.Path" do
    repeated :node, :message, 1, "Hw_Telemetry.PathElem"
  end
  add_message "Hw_Telemetry.PathElem" do
    optional :name, :string, 1
    map :key, :string, :string, 2
  end
  add_message "Hw_Telemetry.Hw_TelemetrySelfDefinedEvent" do
    optional :path, :string, 1
    optional :proto_path, :string, 13
    optional :level, :uint32, 2
    optional :description, :string, 3
    optional :fieldName, :string, 4
    optional :fieldValue, :uint32, 5
    optional :data_threshold, :message, 6, "Hw_Telemetry.Hw_TelemetrySelfDefineThresTable"
    optional :thresholdRelation, :enum, 7, "Hw_Telemetry.Hw_TelemetrySelfDefinedEvent.ThresholdRelation"
    optional :content, :bytes, 8
  end
  add_enum "Hw_Telemetry.Hw_TelemetrySelfDefinedEvent.ThresholdRelation" do
    value :ThresholdRelation_INVALID, 0
    value :ThresholdRelation_AND, 1
    value :ThresholdRelation_OR, 2
  end
  add_message "Hw_Telemetry.Hw_TelemetrySelfDefineThresTable" do
    repeated :row, :message, 1, "Hw_Telemetry.Hw_TelemetryThreshold"
  end
  add_message "Hw_Telemetry.Hw_TelemetryThreshold" do
    optional :thresholdValue, :uint32, 1
    optional :thresholdOpType, :enum, 2, "Hw_Telemetry.Hw_TelemetryThreshold.ThresholdOpType"
  end
  add_enum "Hw_Telemetry.Hw_TelemetryThreshold.ThresholdOpType" do
    value :ThresholdOpType_EQ, 0
    value :ThresholdOpType_GT, 1
    value :ThresholdOpType_GE, 2
    value :ThresholdOpType_LT, 3
    value :ThresholdOpType_LE, 4
  end
end
