# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'google/protobuf/timestamp_pb'
require 'github.com/openconfig/gnmi/proto/gnmi/gnmi_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "telemetry.Telemetry" do
    optional :model_version, :string, 1
    optional :node_id, :string, 2
    optional :subscription_id, :string, 3
    optional :sensor_path, :string, 4
    optional :proto_path, :string, 5
    optional :collection_id, :uint64, 6
    optional :collection_start_time, :message, 7, "google.protobuf.Timestamp"
    optional :msg_timestamp, :message, 8, "google.protobuf.Timestamp"
    repeated :data_gpb, :message, 9, "telemetry.TelemetryData"
    optional :collection_end_time, :message, 10, "google.protobuf.Timestamp"
    optional :except_desc, :string, 11
  end
  add_message "telemetry.TelemetryData" do
    optional :timestamp, :message, 1, "google.protobuf.Timestamp"
    optional :keys, :message, 2, "gnmi.Path"
    optional :content, :message, 3, "google.protobuf.Any"
  end
end

module Telemetry
  Telemetry = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.Telemetry").msgclass
  TelemetryData = Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.TelemetryData").msgclass
end
