# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: huawei-grpc-dialin.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='huawei-grpc-dialin.proto',
  package='huawei_dialin',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x18huawei-grpc-dialin.proto\x12\rhuawei_dialin\"#\n\x04Path\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\r\"\xc8\x01\n\x08SubsArgs\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12\x10\n\x08\x65ncoding\x18\x02 \x01(\r\x12!\n\x04path\x18\x05 \x03(\x0b\x32\x13.huawei_dialin.Path\x12\x17\n\x0fsample_interval\x18\x06 \x01(\x04\x12\x1a\n\x12heartbeat_interval\x18\x07 \x01(\x04\x12\x1c\n\x12suppress_redundant\x18\x08 \x01(\x08H\x00\x12\x14\n\ndelay_time\x18\t \x01(\x04H\x00\x42\n\n\x08Suppress\"\x89\x01\n\tSubsReply\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\r\x12\x12\n\nrequest_id\x18\x02 \x01(\x04\x12\x15\n\rresponse_code\x18\x03 \x01(\t\x12\x11\n\x07message\x18\x04 \x01(\x0cH\x00\x12\x16\n\x0cmessage_json\x18\x05 \x01(\tH\x00\x42\r\n\x0bMessageData\"9\n\nCancelArgs\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12\x17\n\x0fsubscription_id\x18\x02 \x01(\r\"I\n\x0b\x43\x61ncelReply\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12\x15\n\rresponse_code\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\x97\x01\n\x0egRPCConfigOper\x12\x42\n\tSubscribe\x12\x17.huawei_dialin.SubsArgs\x1a\x18.huawei_dialin.SubsReply\"\x00\x30\x01\x12\x41\n\x06\x43\x61ncel\x12\x19.huawei_dialin.CancelArgs\x1a\x1a.huawei_dialin.CancelReply\"\x00\x62\x06proto3'
)




_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='huawei_dialin.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='huawei_dialin.Path.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth', full_name='huawei_dialin.Path.depth', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=78,
)


_SUBSARGS = _descriptor.Descriptor(
  name='SubsArgs',
  full_name='huawei_dialin.SubsArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='huawei_dialin.SubsArgs.request_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='huawei_dialin.SubsArgs.encoding', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='huawei_dialin.SubsArgs.path', index=2,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_interval', full_name='huawei_dialin.SubsArgs.sample_interval', index=3,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heartbeat_interval', full_name='huawei_dialin.SubsArgs.heartbeat_interval', index=4,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='suppress_redundant', full_name='huawei_dialin.SubsArgs.suppress_redundant', index=5,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delay_time', full_name='huawei_dialin.SubsArgs.delay_time', index=6,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Suppress', full_name='huawei_dialin.SubsArgs.Suppress',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=81,
  serialized_end=281,
)


_SUBSREPLY = _descriptor.Descriptor(
  name='SubsReply',
  full_name='huawei_dialin.SubsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscription_id', full_name='huawei_dialin.SubsReply.subscription_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='huawei_dialin.SubsReply.request_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_code', full_name='huawei_dialin.SubsReply.response_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='huawei_dialin.SubsReply.message', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_json', full_name='huawei_dialin.SubsReply.message_json', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MessageData', full_name='huawei_dialin.SubsReply.MessageData',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=284,
  serialized_end=421,
)


_CANCELARGS = _descriptor.Descriptor(
  name='CancelArgs',
  full_name='huawei_dialin.CancelArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='huawei_dialin.CancelArgs.request_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subscription_id', full_name='huawei_dialin.CancelArgs.subscription_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=480,
)


_CANCELREPLY = _descriptor.Descriptor(
  name='CancelReply',
  full_name='huawei_dialin.CancelReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='huawei_dialin.CancelReply.request_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_code', full_name='huawei_dialin.CancelReply.response_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='huawei_dialin.CancelReply.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=555,
)

_SUBSARGS.fields_by_name['path'].message_type = _PATH
_SUBSARGS.oneofs_by_name['Suppress'].fields.append(
  _SUBSARGS.fields_by_name['suppress_redundant'])
_SUBSARGS.fields_by_name['suppress_redundant'].containing_oneof = _SUBSARGS.oneofs_by_name['Suppress']
_SUBSARGS.oneofs_by_name['Suppress'].fields.append(
  _SUBSARGS.fields_by_name['delay_time'])
_SUBSARGS.fields_by_name['delay_time'].containing_oneof = _SUBSARGS.oneofs_by_name['Suppress']
_SUBSREPLY.oneofs_by_name['MessageData'].fields.append(
  _SUBSREPLY.fields_by_name['message'])
_SUBSREPLY.fields_by_name['message'].containing_oneof = _SUBSREPLY.oneofs_by_name['MessageData']
_SUBSREPLY.oneofs_by_name['MessageData'].fields.append(
  _SUBSREPLY.fields_by_name['message_json'])
_SUBSREPLY.fields_by_name['message_json'].containing_oneof = _SUBSREPLY.oneofs_by_name['MessageData']
DESCRIPTOR.message_types_by_name['Path'] = _PATH
DESCRIPTOR.message_types_by_name['SubsArgs'] = _SUBSARGS
DESCRIPTOR.message_types_by_name['SubsReply'] = _SUBSREPLY
DESCRIPTOR.message_types_by_name['CancelArgs'] = _CANCELARGS
DESCRIPTOR.message_types_by_name['CancelReply'] = _CANCELREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), {
  'DESCRIPTOR' : _PATH,
  '__module__' : 'huawei_grpc_dialin_pb2'
  # @@protoc_insertion_point(class_scope:huawei_dialin.Path)
  })
_sym_db.RegisterMessage(Path)

SubsArgs = _reflection.GeneratedProtocolMessageType('SubsArgs', (_message.Message,), {
  'DESCRIPTOR' : _SUBSARGS,
  '__module__' : 'huawei_grpc_dialin_pb2'
  # @@protoc_insertion_point(class_scope:huawei_dialin.SubsArgs)
  })
_sym_db.RegisterMessage(SubsArgs)

SubsReply = _reflection.GeneratedProtocolMessageType('SubsReply', (_message.Message,), {
  'DESCRIPTOR' : _SUBSREPLY,
  '__module__' : 'huawei_grpc_dialin_pb2'
  # @@protoc_insertion_point(class_scope:huawei_dialin.SubsReply)
  })
_sym_db.RegisterMessage(SubsReply)

CancelArgs = _reflection.GeneratedProtocolMessageType('CancelArgs', (_message.Message,), {
  'DESCRIPTOR' : _CANCELARGS,
  '__module__' : 'huawei_grpc_dialin_pb2'
  # @@protoc_insertion_point(class_scope:huawei_dialin.CancelArgs)
  })
_sym_db.RegisterMessage(CancelArgs)

CancelReply = _reflection.GeneratedProtocolMessageType('CancelReply', (_message.Message,), {
  'DESCRIPTOR' : _CANCELREPLY,
  '__module__' : 'huawei_grpc_dialin_pb2'
  # @@protoc_insertion_point(class_scope:huawei_dialin.CancelReply)
  })
_sym_db.RegisterMessage(CancelReply)



_GRPCCONFIGOPER = _descriptor.ServiceDescriptor(
  name='gRPCConfigOper',
  full_name='huawei_dialin.gRPCConfigOper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=558,
  serialized_end=709,
  methods=[
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='huawei_dialin.gRPCConfigOper.Subscribe',
    index=0,
    containing_service=None,
    input_type=_SUBSARGS,
    output_type=_SUBSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Cancel',
    full_name='huawei_dialin.gRPCConfigOper.Cancel',
    index=1,
    containing_service=None,
    input_type=_CANCELARGS,
    output_type=_CANCELREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCCONFIGOPER)

DESCRIPTOR.services_by_name['gRPCConfigOper'] = _GRPCCONFIGOPER

# @@protoc_insertion_point(module_scope)
