# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dialout.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dialout.proto',
  package='dialout',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rdialout.proto\x12\x07\x64ialout\x1a\x19google/protobuf/any.proto\"P\n\x0b\x44ialoutArgs\x12\r\n\x05ReqId\x18\x01 \x01(\x03\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0e\n\x06\x65rrors\x18\x03 \x01(\t2F\n\x07\x44ialout\x12;\n\x07\x44ialout\x12\x14.dialout.DialoutArgs\x1a\x14.dialout.DialoutArgs\"\x00(\x01\x30\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_DIALOUTARGS = _descriptor.Descriptor(
  name='DialoutArgs',
  full_name='dialout.DialoutArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ReqId', full_name='dialout.DialoutArgs.ReqId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='dialout.DialoutArgs.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='dialout.DialoutArgs.errors', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=133,
)

_DIALOUTARGS.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['DialoutArgs'] = _DIALOUTARGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DialoutArgs = _reflection.GeneratedProtocolMessageType('DialoutArgs', (_message.Message,), {
  'DESCRIPTOR' : _DIALOUTARGS,
  '__module__' : 'dialout_pb2'
  # @@protoc_insertion_point(class_scope:dialout.DialoutArgs)
  })
_sym_db.RegisterMessage(DialoutArgs)



_DIALOUT = _descriptor.ServiceDescriptor(
  name='Dialout',
  full_name='dialout.Dialout',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=135,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='Dialout',
    full_name='dialout.Dialout.Dialout',
    index=0,
    containing_service=None,
    input_type=_DIALOUTARGS,
    output_type=_DIALOUTARGS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIALOUT)

DESCRIPTOR.services_by_name['Dialout'] = _DIALOUT

# @@protoc_insertion_point(module_scope)
