# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from openconfig import dialout_pb2 as dialout__pb2

class DialoutStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dialout = channel.stream_stream(
                '/dialout.Dialout/Dialout',
                request_serializer=dialout__pb2.DialoutArgs.SerializeToString,
                response_deserializer=dialout__pb2.DialoutArgs.FromString,
                )


class DialoutServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Dialout(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DialoutServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Dialout': grpc.stream_stream_rpc_method_handler(
                    servicer.Dialout,
                    request_deserializer=dialout__pb2.DialoutArgs.FromString,
                    response_serializer=dialout__pb2.DialoutArgs.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dialout.Dialout', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Dialout(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Dialout(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/dialout.Dialout/Dialout',
            dialout__pb2.DialoutArgs.SerializeToString,
            dialout__pb2.DialoutArgs.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
